# 指定基礎映像檔
FROM python:3.9.7

# 更新apt-get版本&安裝SQLite3
RUN apt-get update && apt-get install -y sqlite3 && apt-get install -y libsqlite3-dev

# 指定Container工作目錄
WORKDIR /usr/src/

# 複製目錄和檔案
COPY ./apps /usr/src/apps
COPY ./local.sqlite /usr/src/local.sqlite
COPY ./requirements.txt /usr/src/requirements.txt

# 在Container內部環境安裝所需的Python套件
RUN pip install --default-timeout=100 -r requirements.txt

# 顯示"building...."的處理程序
RUN echo "building...."

# 設定所需的環境變數
ENV FLASK_APP "apps.app:create_app('local')"

# CMD gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 app:app
# "docker run"執行時的處理程序
CMD ["flask", "run", "-h", "0.0.0.0"]
